databases:
  - name: server
    databaseName: server
    user: server

services:
  - type: web
    name: server
    runtime: python
    buildCommand: "./server/build.sh"
    startCommand: "cd server && gunicorn server.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: server
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4