# Generated by Django 3.2 on 2023-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='createdAt',
            field=models.DateTimeField(),
        ),
    ]
