# Generated by Django 3.2 on 2023-12-13 11:03

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_secret_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='secretText',
            field=api.fields.EncryptedField(),
        ),
    ]
